### ISSUE TITLE
Projekto pavadinimas

### ISSUE THREAD

**Issue by andrius4669** [LukasKrc/FormBackend#1]
Reik sugalvot projekto pavadinimą. Siūlykite idėjas.

**Comment by justinas-linkevicius** [comment]
http://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html
Kadangi mes domain name kaip ir neturim, teks pavadint kažkaip kitaip.
Pvz.: ktu.forms.backend ?

**Comment by andrius4669** [comment]
na, visu pirma tai butu lt.ktu.forms.backend; antra, mums reikia sugaloti koki nors varda. "forms" nera vardas - net jei ir kolkas neturim domeno vardo.
